 # Project language
language: php
 # Allows use container-based infrastructure
sudo: false
 # Start mysql service
services:
  - mysql
 # Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
 # Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: 
  include:
    - php: 7.2
 # Define an environment variable
env:
  - SYMFONY_VERSION="4.1.*" DB=mysql DATABASE_URL=mysql://root:@127.0.0.1:3306/Pyoupyou
 # Update composer
before-install:
  - composer self-update
 # Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp .env.dist .env
  - cp phpunit.xml.travis phpunit.xml
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - composer i
  - bin/console app:install
 # Run script
script
  - bin/phpunit --verbose
 # After a build, send email notification with the build results
notifications:
  email: julien.seixas@free.fr

